# Set the token in Travis environment settings instead defining here.

language: go

go:
  - "1.10"
  - 1.11.x
  - master

env:
  - DB=postgres DB_VERSION=9.6
  - DB=postgres DB_VERSION=10
  - DB=postgres DB_VERSION=11
  - DB=postgres DB_VERSION=latest

services:
  - docker

before_install:
  - docker run --name postgres -p 127.0.0.1:15432:5432 -e POSTGRES_USER=efureev -e POSTGRES_DB=test -d postgres:${DB_VERSION}
  - go get -t -v ./...

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - PG_PORT=15432 PG_USERNAME=efureev go test -coverprofile c.out ./...
  - PG_PORT=15432 PG_USERNAME=efureev go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)